FROM gradle:7.3.3-jdk11 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src

RUN gradle build --no-daemon

CMD sh

FROM openjdk:11-jdk-alpine
EXPOSE 8090
RUN mkdir /app

COPY --from=build /home/gradle/src/build/libs/*.jar /app/$ARTIFACT_JAR
ENTRYPOINT ["java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app/$ARTIFACT_JAR"]
